export const AGREGAR_PRODUCTO_CARRITO = "AGREGAR_PRODUCTO_CARRITO";
export const ELIMINAR_PRODUCTO_CARRITO = "ELIMINAR_PRODUCTO_CARRITO";
export const VACIAR_CARRITO = "VACIAR_CARRITO";
export const INCREMENTAR_ITEM = "INCREMENTAR_ITEM";
export const DECREMENTAR_ITEM = "DECREMENTAR_ITEM";
export const AGREGAR_PEDIDO = "AGREGAR_PEDIDO";