export const FETCH_PRODUCTO_CATALOGO = "FETCH_PRODUCTO_CATALOGO"; 
export const FETCH_PRODUCTO_CATALOGO_SUCCESS = "FETCH_PRODUCTO_CATALOGO_SUCCESS"; 
export const FETCH_PRODUCTO_CATALOGO_ERROR = "FETCH_PRODUCTO_CATALOGO_ERROR"; 
export const AGREGAR_PRODUCTO_CATALOGO = "AGREGAR_PRODUCTO_CATALOGO";
export const ACTUALIZAR_PRODUCTO_CATALOGO = "ACTUALIZAR_PRODUCTO_CATALOGO";
export const ELIMINAR_PRODUCTO_CATALOGO = "ELIMINAR_PRODUCTO_CATALOGO";