export const AGREGAR_PRODUCTO_CATALOGO = "AGREGAR_PRODUCTO_CATALOGO";
export const ACTUALIZAR_PRODUCTO_CATALOGO = "ACTUALIZAR_PRODUCTO_CATALOGO";
export const ELIMINAR_PRODUCTO_CATALOGO = "ELIMINAR_PRODUCTO_CATALOGO";