import { AGREGAR_PEDIDO, AGREGAR_PRODUCTO_CARRITO, DECREMENTAR_ITEM, ELIMINAR_PRODUCTO_CARRITO, INCREMENTAR_ITEM, VACIAR_CARRITO } from "../types/CarritoTypes";

export const AGREGAR_PRODUCTO_CARRITO_ACTION = (id) => ({type:AGREGAR_PRODUCTO_CARRITO, payload:id});
export const ELIMINAR_PRODUCTO_CARRITO_ACTION = (id) => ({type:ELIMINAR_PRODUCTO_CARRITO, payload:id});
export const VACIAR_CARRITO_ACTION = {type:VACIAR_CARRITO};
export const INCREMENTAR_ITEM_ACTION = (id) => ({type:INCREMENTAR_ITEM, payload:id});
export const DECREMENTAR_ITEM_ACTION = (id) => ({type:DECREMENTAR_ITEM, payload:id});
export const AGREGAR_PEDIDO_ACTION = {type:AGREGAR_PEDIDO};